#+BEGIN_SRC
In [1]: from transformers import AutoModelForCausalLM, AutoTokenizer

In [3]: model_id = "mistralai/Mixtral-8x7B-Instruct-v0.1"

In [4]: tokenizer = AutoTokenizer.from_pretrained(model_id)

In [5]: model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto")
Loading checkpoint shards: 100%|██████████████████████████| 19/19 [03:15<00:00, 10.31s/it]generation_config.json: 100%|█████████████████████████████| 116/116 [00:00<00:00, 376kB/s]WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.

In [6]: messages = [
   ...:     {"role": "user", "content": "What is your favourite condiment?"},
   ...:     {"role": "assistant", "content": "Well, I'm quite partial to a good squeeze of   ...:  fresh lemon juice. It adds just the right amount of zesty flavour to whatever I'm   ...:  cooking up in the kitchen!"},
   ...:     {"role": "user", "content": "Do you have mayonnaise recipes?"}
   ...: ]

In [7]: inputs = tokenizer.apply_chat_template(messages, return_tensors="pt").to("cuda")

In [8]: outputs = model.generate(inputs, max_new_tokens=20)
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

In [9]: print(tokenizer.decode(outputs[0], skip_special_tokens=True))

[INST] What is your favourite condiment? [/INST]Well, I'm quite partial to a good squeeze of fresh lemon juice. It adds just the right amount of zesty flavour to whatever I'm cooking up in the kitchen! [INST] Do you have mayonnaise recipes? [/INST] Yes, I do have a simple mayonnaise recipe that I enjoy making. Here it is:

In [10]: new_messages = [
    ...:     {"role": "user", "content": "What are some applications of mathematics in med    ...: icine?"},
    ...:     {"role": "assistant", "content": "Fluid dynamics has applications in analyzin    ...: g blood flow, and a more advanced and recent example, algebraic statistics has ap    ...: plications in phyologeny"},
    ...:     {"role": "user", "content": "Can you tell me more about algebraic statistics     ...: and its relationship to phylogeny?"}
    ...: ]

In [11]: new_inputs = tokenizer.apply_chat_template(new_messages, return_tensors="pt").to(    ...: "cuda")

In [12]: new_outputs = model.generate(new_inputs)
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
/home/ch231037/miniconda3/envs/hf_latest/lib/python3.12/site-packages/transformers/generation/utils.py:1168: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 1
----> 1 new_outputs = model.generate(new_inputs)

File ~/miniconda3/envs/hf_latest/lib/python3.12/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/miniconda3/envs/hf_latest/lib/python3.12/site-packages/transformers/generation/utils.py:1648, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1642             raise ValueError(
   1643                 "This model does not support `cache_implementation='static'`. Please check the following "
   1644                 "issue: https://github.com/huggingface/transformers/issues/28981"
   1645             )
   1646         model_kwargs["past_key_values"] = self._get_static_cache(batch_size, generation_config.max_length)
-> 1648 self._validate_generated_length(generation_config, input_ids_length, has_default_max_length)
   1650 # 7. determine generation mode
   1651 generation_mode = generation_config.get_generation_mode(assistant_model)

File ~/miniconda3/envs/hf_latest/lib/python3.12/site-packages/transformers/generation/utils.py:1176, in GenerationMixin._validate_generated_length(self, generation_config, input_ids_length, has_default_max_length)
   1174 if input_ids_length >= generation_config.max_length:
   1175     input_ids_string = "decoder_input_ids" if self.config.is_encoder_decoder else "input_ids"
-> 1176     raise ValueError(
   1177         f"Input length of {input_ids_string} is {input_ids_length}, but `max_length` is set to"
   1178         f" {generation_config.max_length}. This can lead to unexpected behavior. You should consider"
   1179         " increasing `max_length` or, better yet, setting `max_new_tokens`."
   1180     )
   1182 # 2. Min length warnings due to unfeasible parameter combinations
   1183 min_length_error_suffix = (
   1184     " Generation will stop at the defined maximum length. You should decrease the minimum length and/or "
   1185     "increase the maximum length."
   1186 )

ValueError: Input length of input_ids is 73, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.

In [13]: new_outputs = model.generate(new_inputs, max_new_tokens=128)
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

In [11]: new_inputs = tokenizer.apply_chat_template(new_messages, return_tensors="pt").to(    ...: "cuda")
